USE [master];
IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = '$DB_NAME')
BEGIN
    CREATE DATABASE [$DB_NAME]
END
GO

USE [$DB_NAME]
IF NOT EXISTS (SELECT * FROM sys.sql_logins WHERE [name] = '$DB_USERNAME')
BEGIN
    CREATE LOGIN [$DB_USERNAME] WITH PASSWORD = '$DB_PASSWORD'

    CREATE USER [$DB_USERNAME] FOR LOGIN [$DB_USERNAME]

    EXEC sp_addrolemember N'db_owner', N'$DB_USERNAME'
END
GO
